CREATE TABLE  IF NOT EXISTS app_user (
  ID SERIAL PRIMARY KEY,
  EMAIL TEXT NOT NULL,
  LOGIN TEXT NOT NULL,
  FIRST_NAME TEXT,
  LAST_NAME TEXT
);

CREATE TABLE IF NOT EXISTS item (
  ID SERIAL PRIMARY KEY,
  NAME TEXT NOT NULL,
  COST INTEGER NOT NULL,
  DESCRIPTION TEXT,
  IMAGE_URL TEXT
);